language: php
php:
  - '7.2'
os: 'linux'
dist: 'bionic'
before_install:
  - 'composer install'
  - 'composer update'
  - 'cp .env.example .env'
  - 'php artisan key:generate'
  - 'php artisan migrate'
install:
  - 'php artisan passport:install'