language: php

php:
  - '7.2'

os: 'linux'

dist: 'bionic'

before_install:
  - 'cp .env.example .env'
  - mysql -e 'create database restful_oauth_testing;'
  - mysql -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -e "GRANT ALL PRIVILEGES ON restful_oauth_testing . * TO 'homestead'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"
  - 'composer install'
  - 'php artisan key:generate'
  - 'php artisan migrate --database=mysql_testing'

install:
  - 'php artisan passport:install'

services:
  - mysql

cache:
  directories:
    - vendor
